"""HTML, PDF, map, and plot generation for OpenWind-AU."""

from __future__ import annotations

import json
from pathlib import Path

import folium
import plotly.graph_objects as go
from jinja2 import Template
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from openwind_au.geo import destination_point
from openwind_au.models import ObstructionInventoryResult, SiteAnalysisResult

REPORT_TEMPLATE = Template(
    """
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>OpenWind-AU Preliminary Terrain Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 32px; color: #202124; }
    h1, h2 { color: #17324d; }
    table { border-collapse: collapse; width: 100%; margin: 16px 0; }
    th, td { border: 1px solid #d0d7de; padding: 8px; text-align: left; }
    th { background: #f6f8fa; }
    .disclaimer { border-left: 4px solid #b42318; padding: 12px; background: #fff4f2; }
    .note { color: #57606a; font-size: 0.95em; }
  </style>
</head>
<body>
  <h1>OpenWind-AU Preliminary Terrain Report</h1>
  <p class="disclaimer">{{ result.disclaimer }}</p>

  <h2>Site</h2>
  <table>
    <tr><th>Latitude</th><td>{{ "%.6f"|format(result.site.latitude) }}</td></tr>
    <tr><th>Longitude</th><td>{{ "%.6f"|format(result.site.longitude) }}</td></tr>
    <tr><th>Ground elevation</th><td>{{ "%.2f"|format(result.site.ground_elevation_m) }} m</td></tr>
    <tr><th>Building height</th><td>{{ "%.2f"|format(result.input.building_height_m) }} m</td></tr>
    <tr><th>Location source</th><td>{{ result.site.source }}</td></tr>
  </table>

  <h2>Preliminary Topographic Screening</h2>
  <table>
    <tr>
      <th>Direction</th><th>Azimuth</th><th>Feature</th><th>Site RL</th><th>Crest RL</th>
      <th>Base RL</th><th>H</th><th>Lu</th><th>x</th><th>Average upwind slope</th>
      <th>Confidence</th><th>Notes</th>
    </tr>
    {% for feature in result.features %}
    <tr>
      <td>{{ feature.direction }}</td>
      <td>{{ "%.0f"|format(feature.azimuth_deg) }} deg</td>
      <td>{{ feature.feature_type }}</td>
      <td>{{ "%.2f"|format(feature.site_rl_m) }} m</td>
      <td>{{ "%.2f"|format(feature.crest_rl_m) }} m</td>
      <td>{{ "%.2f"|format(feature.base_rl_m) }} m</td>
      <td>{{ "%.2f"|format(feature.h_m) }} m</td>
      <td>{{ "%.1f"|format(feature.lu_m) }} m</td>
      <td>{{ "%.1f"|format(feature.x_m) }} m</td>
      <td>{{ "%.3f"|format(feature.average_upwind_slope) }}</td>
      <td>{{ feature.confidence }}</td>
      <td>{{ feature.notes|join(" ") }}</td>
    </tr>
    {% endfor %}
  </table>

  <h2>Terrain Profile Summary</h2>
  <table>
    <tr>
      <th>Direction</th><th>Azimuth</th><th>Endpoint</th><th>Min RL</th>
      <th>Max RL</th><th>Average slope</th>
    </tr>
    {% for profile in result.profiles %}
    <tr>
      <td>{{ profile.direction }}</td>
      <td>{{ "%.0f"|format(profile.azimuth_deg) }} deg</td>
      <td>
        {{ "%.6f"|format(profile.endpoint_latitude) }},
        {{ "%.6f"|format(profile.endpoint_longitude) }}
      </td>
      <td>{{ "%.2f"|format(profile.min_elevation_m) }} m</td>
      <td>{{ "%.2f"|format(profile.max_elevation_m) }} m</td>
      <td>{{ "%.4f"|format(profile.average_slope) }}</td>
    </tr>
    {% endfor %}
  </table>

  <h2>Assumptions</h2>
  <ul>{% for item in result.assumptions %}<li>{{ item }}</li>{% endfor %}</ul>

  <h2>Limitations</h2>
  <ul>{% for item in result.limitations %}<li>{{ item }}</li>{% endfor %}</ul>

  <p class="note">
    Generated by OpenWind-AU. This report is preliminary and requires engineering review.
  </p>
</body>
</html>
"""
)


def result_to_json(result: SiteAnalysisResult) -> dict:
    """Convert an analysis result into JSON-serialisable data."""

    return json.loads(result.model_dump_json())


def render_html_report(result: SiteAnalysisResult) -> str:
    """Render an HTML report string."""

    return REPORT_TEMPLATE.render(result=result)


def write_html_report(result: SiteAnalysisResult, path: Path) -> Path:
    """Write an HTML report to *path*."""

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_html_report(result), encoding="utf-8")
    return path


def write_pdf_report(result: SiteAnalysisResult, path: Path) -> Path:
    """Write a simple PDF report to *path* using ReportLab."""

    path.parent.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(str(path), pagesize=A4)
    styles = getSampleStyleSheet()
    story = [
        Paragraph("OpenWind-AU Preliminary Terrain Report", styles["Title"]),
        Paragraph(result.disclaimer, styles["BodyText"]),
        Spacer(1, 12),
        Paragraph("Site", styles["Heading2"]),
        Table(
            [
                ["Latitude", f"{result.site.latitude:.6f}"],
                ["Longitude", f"{result.site.longitude:.6f}"],
                ["Ground elevation", f"{result.site.ground_elevation_m:.2f} m"],
                ["Building height", f"{result.input.building_height_m:.2f} m"],
                ["Location source", result.site.source],
            ],
            hAlign="LEFT",
        ),
        Spacer(1, 12),
        Paragraph("Preliminary Topographic Screening", styles["Heading2"]),
    ]
    feature_rows = [
        [
            "Dir.",
            "Az.",
            "Feature",
            "Site RL",
            "Crest RL",
            "Base RL",
            "H",
            "Lu",
            "x",
            "Slope",
            "Conf.",
        ]
    ]
    for feature in result.features:
        feature_rows.append(
            [
                feature.direction,
                f"{feature.azimuth_deg:.0f}",
                feature.feature_type,
                f"{feature.site_rl_m:.1f}",
                f"{feature.crest_rl_m:.1f}",
                f"{feature.base_rl_m:.1f}",
                f"{feature.h_m:.1f}",
                f"{feature.lu_m:.0f}",
                f"{feature.x_m:.0f}",
                f"{feature.average_upwind_slope:.3f}",
                feature.confidence,
            ]
        )
    table = Table(feature_rows, repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("FONT", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 7),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 8))
    story.append(
        Paragraph(
            "Candidate topographic features require review by a competent engineer.",
            styles["BodyText"],
        )
    )
    profile_rows = [["Dir.", "Az.", "Min RL", "Max RL", "Avg slope"]]
    for profile in result.profiles:
        profile_rows.append(
            [
                profile.direction,
                f"{profile.azimuth_deg:.0f}",
                f"{profile.min_elevation_m:.1f}",
                f"{profile.max_elevation_m:.1f}",
                f"{profile.average_slope:.4f}",
            ]
        )
    profile_table = Table(profile_rows, repeatRows=1)
    profile_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("FONT", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.extend(
        [
            Spacer(1, 12),
            Paragraph("Terrain Profile Summary", styles["Heading2"]),
            profile_table,
            Spacer(1, 12),
            Paragraph("Assumptions", styles["Heading2"]),
            *[Paragraph(f"- {item}", styles["BodyText"]) for item in result.assumptions],
            Spacer(1, 12),
            Paragraph("Limitations", styles["Heading2"]),
            *[Paragraph(f"- {item}", styles["BodyText"]) for item in result.limitations],
        ]
    )
    doc.build(story)
    return path


def profile_plot_html(result: SiteAnalysisResult) -> str:
    """Return a Plotly HTML fragment for terrain profile plots."""

    fig = go.Figure()
    features_by_direction = {feature.direction: feature for feature in result.features}
    for profile in result.profiles:
        feature = features_by_direction.get(profile.direction)
        fig.add_trace(
            go.Scatter(
                x=[point.distance_m for point in profile.points],
                y=[point.elevation_m for point in profile.points],
                mode="lines",
                name=f"{profile.direction} ({profile.azimuth_deg:.0f} deg)",
                hovertemplate=(
                    f"{profile.direction}<br>"
                    "Distance: %{x:.0f} m<br>"
                    "RL: %{y:.2f} m<extra></extra>"
                ),
            )
        )
        if not feature:
            continue

        fig.add_trace(
            go.Scatter(
                x=[0],
                y=[feature.site_rl_m],
                mode="markers",
                name=f"{profile.direction} site",
                marker={"symbol": "circle", "size": 8, "color": "#0f766e"},
                hovertemplate=(
                    f"{profile.direction} site<br>Distance: 0 m<br>RL: %{{y:.2f}} m<extra></extra>"
                ),
                showlegend=False,
            )
        )
        if feature.feature_type == "no significant feature":
            continue

        fig.add_trace(
            go.Scatter(
                x=[feature.base_x_m],
                y=[feature.base_rl_m],
                mode="markers",
                name=f"{profile.direction} candidate base",
                marker={"symbol": "square", "size": 8, "color": "#f59e0b"},
                hovertemplate=(
                    f"{profile.direction} base<br>"
                    "Distance: %{x:.0f} m<br>"
                    "RL: %{y:.2f} m<extra></extra>"
                ),
                showlegend=False,
            )
        )
        fig.add_trace(
            go.Scatter(
                x=[feature.crest_x_m],
                y=[feature.crest_rl_m],
                mode="markers",
                name=f"{profile.direction} candidate crest",
                marker={"symbol": "diamond", "size": 9, "color": "#b42318"},
                hovertemplate=(
                    f"{profile.direction} crest<br>"
                    "Distance: %{x:.0f} m<br>"
                    "RL: %{y:.2f} m<extra></extra>"
                ),
                showlegend=False,
            )
        )
        fig.add_trace(
            go.Scatter(
                x=[feature.crest_x_m, feature.crest_x_m],
                y=[feature.base_rl_m, feature.crest_rl_m],
                mode="lines",
                name=f"{profile.direction} H",
                line={"color": "#b42318", "width": 2, "dash": "dot"},
                hovertemplate=f"H: {feature.h_m:.2f} m<extra></extra>",
                showlegend=False,
            )
        )
        fig.add_trace(
            go.Scatter(
                x=[feature.base_x_m, feature.crest_x_m],
                y=[feature.base_rl_m, feature.base_rl_m],
                mode="lines",
                name=f"{profile.direction} Lu",
                line={"color": "#f59e0b", "width": 2, "dash": "dash"},
                hovertemplate=f"Lu: {feature.lu_m:.1f} m<extra></extra>",
                showlegend=False,
            )
        )
    fig.update_layout(
        title="Radial terrain profiles with preliminary topographic screening overlays",
        xaxis_title="Distance from site (m)",
        yaxis_title="Elevation RL (m)",
        template="plotly_white",
    )
    return fig.to_html(full_html=False, include_plotlyjs="cdn")


def map_html(result: SiteAnalysisResult) -> str:
    """Return a Folium map HTML document for the site and detected features."""

    fmap = folium.Map(
        location=[result.site.latitude, result.site.longitude],
        zoom_start=13,
        control_scale=True,
    )
    folium.Marker(
        [result.site.latitude, result.site.longitude],
        tooltip="Site",
        popup=f"Ground RL {result.site.ground_elevation_m:.1f} m",
    ).add_to(fmap)
    folium.Circle(
        location=[result.site.latitude, result.site.longitude],
        radius=result.input.radius_m,
        color="#0f766e",
        weight=2,
        fill=False,
        tooltip=f"Analysis radius: {result.input.radius_m} m",
    ).add_to(fmap)
    for profile in result.profiles:
        coordinates = [(point.latitude, point.longitude) for point in profile.points]
        folium.PolyLine(
            locations=coordinates,
            color="#17324d",
            weight=2,
            opacity=0.75,
            tooltip=f"{profile.direction} profile ({profile.azimuth_deg:.0f} deg)",
        ).add_to(fmap)
        folium.CircleMarker(
            location=[profile.endpoint_latitude, profile.endpoint_longitude],
            radius=4,
            color="#0f766e",
            fill=True,
            fill_opacity=0.85,
            tooltip=f"{profile.direction} endpoint",
            popup=(
                f"{profile.direction} endpoint<br>"
                f"Azimuth {profile.azimuth_deg:.0f} deg<br>"
                f"Radius {profile.radius_m} m"
            ),
        ).add_to(fmap)
    for feature in result.features:
        if feature.feature_type == "no significant feature":
            continue
        feature_lat, feature_lon = destination_point(
            result.site.latitude,
            result.site.longitude,
            feature.azimuth_deg,
            feature.x_m,
        )
        folium.CircleMarker(
            location=[feature_lat, feature_lon],
            radius=5,
            color="#b42318",
            fill=True,
            tooltip=f"{feature.feature_type} {feature.azimuth_deg:.0f} deg",
            popup=(
                f"{feature.feature_type}: H={feature.h_m:.1f} m, "
                f"Lu={feature.lu_m:.0f} m, x={feature.x_m:.0f} m"
            ),
        ).add_to(fmap)
    return fmap.get_root().render()


def obstruction_map_html(result: ObstructionInventoryResult) -> str:
    """Return a Folium map HTML document for obstruction footprint review."""

    fmap = folium.Map(
        location=[result.site.latitude, result.site.longitude],
        zoom_start=16,
        control_scale=True,
    )
    folium.Marker(
        [result.site.latitude, result.site.longitude],
        tooltip="Subject site",
        popup="Subject site",
    ).add_to(fmap)
    folium.Circle(
        location=[result.site.latitude, result.site.longitude],
        radius=result.input.radius_m,
        color="#17324d",
        weight=2,
        fill=False,
        tooltip=f"Obstruction inventory radius: {result.input.radius_m} m",
    ).add_to(fmap)
    for obstruction in result.obstructions:
        color = _obstruction_color(obstruction.confidence)
        folium.GeoJson(
            obstruction.footprint_geometry,
            style_function=lambda _feature, color=color: {
                "color": color,
                "weight": 2,
                "fillColor": color,
                "fillOpacity": 0.25,
            },
            tooltip=(
                f"{obstruction.obstruction_id}: {obstruction.height_m:.1f} m"
                if obstruction.height_m is not None
                else f"{obstruction.obstruction_id}: height missing"
            ),
        ).add_to(fmap)
        folium.CircleMarker(
            location=[obstruction.centroid_latitude, obstruction.centroid_longitude],
            radius=3,
            color=color,
            fill=True,
            popup=(
                f"{obstruction.obstruction_id}<br>"
                f"Distance {obstruction.distance_m:.1f} m<br>"
                f"Bearing {obstruction.bearing_deg:.0f} deg<br>"
                f"Height source {obstruction.height_source}<br>"
                f"Confidence {obstruction.confidence}"
            ),
        ).add_to(fmap)
    return fmap.get_root().render()


def render_obstruction_report_html(result: ObstructionInventoryResult) -> str:
    """Render an HTML obstruction inventory report."""

    return OBSTRUCTION_REPORT_TEMPLATE.render(result=result)


def _obstruction_color(confidence: str) -> str:
    return {
        "verified": "#047857",
        "high": "#0f766e",
        "medium": "#b45309",
        "unknown": "#b42318",
    }.get(confidence, "#57606a")


OBSTRUCTION_REPORT_TEMPLATE = Template(
    """
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>OpenWind-AU Obstruction Inventory Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 32px; color: #202124; }
    h1, h2 { color: #17324d; }
    table { border-collapse: collapse; width: 100%; margin: 16px 0; }
    th, td { border: 1px solid #d0d7de; padding: 8px; text-align: left; }
    th { background: #f6f8fa; }
    .disclaimer { border-left: 4px solid #b42318; padding: 12px; background: #fff4f2; }
  </style>
</head>
<body>
  <h1>OpenWind-AU Obstruction Inventory Report</h1>
  <p class="disclaimer">{{ result.disclaimer }}</p>

  <h2>Subject Site</h2>
  <table>
    <tr><th>Latitude</th><td>{{ "%.6f"|format(result.site.latitude) }}</td></tr>
    <tr><th>Longitude</th><td>{{ "%.6f"|format(result.site.longitude) }}</td></tr>
    <tr><th>Inventory radius</th><td>{{ result.input.radius_m }} m</td></tr>
    <tr>
      <th>Default storey height</th>
      <td>{{ "%.2f"|format(result.input.default_storey_height_m) }} m</td>
    </tr>
  </table>

  <h2>Missing Height Summary</h2>
  <table>
    <tr><th>Total obstructions</th><th>Missing heights</th><th>Reviewed heights</th></tr>
    <tr>
      <td>{{ result.obstructions|length }}</td>
      <td>{{ result.missing_height_count }}</td>
      <td>{{ result.reviewed_height_count }}</td>
    </tr>
  </table>

  <h2>Obstruction Map</h2>
  <p>
    Use <code>POST /api/obstructions/map</code> for the interactive footprint map. Footprints are
    coloured by height confidence.
  </p>

  <h2>Obstruction Table</h2>
  <table>
    <tr>
      <th>ID</th><th>Distance</th><th>Bearing</th><th>Height</th><th>Levels</th>
      <th>Source</th><th>Confidence</th><th>Manual review</th>
    </tr>
    {% for obstruction in result.obstructions %}
    <tr>
      <td>{{ obstruction.obstruction_id }}</td>
      <td>{{ "%.1f"|format(obstruction.distance_m) }} m</td>
      <td>{{ "%.0f"|format(obstruction.bearing_deg) }} deg</td>
      <td>
        {% if obstruction.height_m is not none %}
        {{ "%.2f"|format(obstruction.height_m) }} m
        {% else %}
        missing
        {% endif %}
      </td>
      <td>{{ obstruction.building_levels if obstruction.building_levels is not none else "" }}</td>
      <td>{{ obstruction.height_source }}</td>
      <td>{{ obstruction.confidence }}</td>
      <td>{{ obstruction.manual_review_required }}</td>
    </tr>
    {% endfor %}
  </table>

  <p>
    Ms cannot be assessed without reliable obstruction heights. This report is an inventory for
    shielding input review only.
  </p>
</body>
</html>
"""
)
